<script src="theme/js/jquery.js"></script>
<!--Revolution Slider-->
<script src="theme/plugins/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="theme/plugins/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="theme/plugins/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="theme/js/main-slider-script.js"></script>

<script src="theme/js/modernizr.min.js"></script>
<script src="theme/js/bootstrap.min.js"></script>
<script src="theme/js/jquery.fancybox.pack.js"></script>
<script src="theme/js/jquery.fancybox-media.js"></script>
<script src="theme/js/owl.js"></script>
<script src="theme/js/mixitup.js"></script>
<script src="theme/js/appear.js"></script>
<script src="theme/js/script.js"></script>